version: "2"
services:
  mi:
    container_name: mi
    image: dushansilva/test:1.0
    ports:
      - "8253:8253"
      - "8290:8290"
  backend1:
    container_name: backend1
    restart: always
    build: ./backend/
    ports:
      - "3000:3000"
    command: ["npm" ,"run","start-dev"]
